#line 1 "../main.ino"
#include <Arduino.h>
#line 1
void setup ();
void loop ();
#line 1
/* Main.ino file generated by New Project wizard
 *
 * Created:   Пн мар 28 2016
 * Processor: ATmega328P
 * Compiler:  Arduino AVR
 */

 int buttonState = 0;
 int c1r1 = 0;
 int c1r2 = 0;
 int c1r3 = 0;
 int c2r1 = 0;
 int c2r2 = 0;
 int c2r3 = 0;
 
void setup()
 { // put your setup code here, to run once:
   // инициализируем пин, подключенный к светодиоду, как выход
  pinMode(13, OUTPUT);
  pinMode(12, INPUT);
  
  pinMode(1, INPUT);
  pinMode(2, INPUT);
  pinMode(3, INPUT);
  //------------------
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  //------------------
  pinMode(6, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(11, OUTPUT);
 }

void loop()
 { // put your main code here, to run repeatedly
  
  //===========================================================================================
  digitalWrite(4, HIGH);	// подаем сканирующее напряжение (логич. 1) на шину (колонку) 1
  c1r1 = digitalRead(1);	// снимаем значение с кнопки 1-й строки 1-й колонки
  c1r2 = digitalRead(2);	// снимаем значение с кнопки 2-й строки 1-й колонки
  c1r3 = digitalRead(3);	// снимаем значение с кнопки 3-й строки 1-й колонки
  digitalWrite(4, LOW);		// убираем сканирующее питание
  //---------------------
  if (c1r1 == 1) {
   digitalWrite(6, HIGH);	// зажигаем светодиод
  }
  else {
   digitalWrite(6, LOW);	// выключаем светодиод
  }
  //---------------------
  if (c1r2 == 1) {
   digitalWrite(7, HIGH);	// зажигаем светодиод
  }
  else {
   digitalWrite(7, LOW);	// выключаем светодиод
  }
  //---------------------
  if (c1r3 == 1) {
   digitalWrite(8, HIGH);	// зажигаем светодиод
  }
  else {
   digitalWrite(8, LOW);	// выключаем светодиод
  }
  
  //===========================================================================================
  digitalWrite(5, HIGH);	// подаем сканирующее напряжение (логич. 1) на шину (колонку) 2
  c2r1 = digitalRead(1);	// снимаем значение с кнопки 1-й строки 2-й колонки
  c2r2 = digitalRead(2);	// снимаем значение с кнопки 2-й строки 2-й колонки
  c2r3 = digitalRead(3);	// снимаем значение с кнопки 3-й строки 2-й колонки
  digitalWrite(5, LOW);		// убираем сканирующее питание
  //---------------------
  if (c2r1 == 1) {
   digitalWrite(9, HIGH);	// зажигаем светодиод
  }
  else {
   digitalWrite(9, LOW);	// выключаем светодиод
  }
  //---------------------
  if (c2r2 == 1) {
   digitalWrite(10, HIGH);	// зажигаем светодиод
  }
  else {
   digitalWrite(10, LOW);	// выключаем светодиод
  }
  //---------------------
  if (c2r3 == 1) {
   digitalWrite(11, HIGH);	// зажигаем светодиод
  }
  else {
   digitalWrite(11, LOW);	// выключаем светодиод
  }

  }
 